name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! I deploy with new version"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l