# fly.toml app configuration file generated for phonebook-wa-cicd on 2024-05-11T19:24:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-wa-cicd'
primary_region = 'sin'

[env]
  PORT = "3000"

[processes]
  app = "node index.js" # add this

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
